Bump SnakeYAML to 2.0 (CVE) & Liquibase to 4.21.1 (compatible)
This is to allow dependent projects to use SnakeYAML 2.0, which fixes a
security vulnerability in prior versions:
[CVE-2022-1471](https://www.veracode.com/blog/research/resolving-cve-2022-1471-snakeyaml-20-release-0)
> In October of 2022, a
> [critical flaw](https://nvd.nist.gov/vuln/detail/CVE-2022-1471) was
> found in the SnakeYAML package, which allowed an attacker to benefit
> from remote code execution by sending malicious YAML content and this
> content being deserialized by the constructor.

Liquibase must be upgraded as well since it's impacted by a breaking API
change in SnakeYAML 2.0:
```java
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
  at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:24)
  at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
  [...]
```
Considered Liquibase versions:
- [4.19.0](https://github.com/liquibase/liquibase/releases/tag/v4.19.0):
  > [...] We are currently on the newest version of snakeyaml and there
  > is no fix for the issue as of yet.
- [4.19.1](https://github.com/liquibase/liquibase/releases/tag/v4.19.1):
  > [....] users can manually upgrade to the newest version of snakeyaml
  > library, and will be upgraded to the unaffected snakeyaml 2.0 version
  > in the next release.
- [4.20.0](https://github.com/liquibase/liquibase/releases/tag/v4.20.0):
  > Fixes
  > - Safely call snakeyaml methods that have been changed in last
  >   versions.
- [4.21.0](https://github.com/liquibase/liquibase/releases/tag/v4.21.0):
  > Fixes
  > - Rollback Snakeyaml default config to allow duplicate keys [...]
- **proposed here**,
  [4.21.1](https://github.com/liquibase/liquibase/releases/tag/v4.21.1):
  > Liquibase 4.21.1 is a patch release
- [4.22.0](https://github.com/liquibase/liquibase/releases/tag/v4.22.0):
  > We have removed the 4.22.0 release of Liquibase.

The present change consists in bumping these versions and adapt to
trivial API changes.

The test runtime requires a more recent version of `picocli` than the
transitively obtained one.